FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libglew-dev libglfw3-dev cmake gcc libcurl4-gnutls-dev tesseract-ocr libtesseract-dev libleptonica-dev clang libclang-dev libgpac-dev

RUN printf '%s\n' \
    '#ifndef GF_ISOM_MEDIA_CLOSED_CAPTION' \
    "#define GF_ISOM_MEDIA_CLOSED_CAPTION GF_4CC('c','l','c','p')" \
    '#endif' \
    '#ifndef GF_ISOM_SUBTYPE_XDVB' \
    "#define GF_ISOM_SUBTYPE_XDVB GF_4CC('x','d','v','b')" \
    '#endif' \
    '#ifndef GF_ISOM_SUBTYPE_TX3G' \
    "#define GF_ISOM_SUBTYPE_TX3G GF_4CC('t','x','3','g')" \
    '#endif' \
    '#ifndef GF_QT_SUBTYPE_C608' \
    "#define GF_QT_SUBTYPE_C608 GF_4CC('c','6','0','8')" \
    '#endif' \
    '#ifndef GF_ISOM_SUBTYPE_TEXT' \
    "#define GF_ISOM_SUBTYPE_TEXT GF_4CC('t','e','x','t')" \
    '#endif' \
    >> /usr/include/gpac/isomedia.h

COPY . /repo
WORKDIR /repo/linux
RUN ./build -without-rust

FROM ubuntu:20.04 as package
COPY --from=builder /repo/linux/ccextractor /repo/linux/ccextractor

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libtesseract-dev
